services:
  watchtower:
    container_name: watchtower
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  proxy:
    container_name: proxy
    restart: always
    image: nginxproxy/nginx-proxy
    env_file: ./proxy/.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/docker-data/nginx-proxy/html/:/usr/share/nginx/html/
      - ./proxy/docker-data/nginx-proxy/vhost.d/:/etc/nginx/vhost.d/
      - ./proxy/docker-data/acme-companion/certs/:/etc/nginx/certs/:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  proxy-acme:
    container_name: proxy-acme
    restart: always
    image: nginxproxy/acme-companion
    env_file: ./proxy/.env
    volumes_from:
      - proxy
    volumes:
      - ./proxy/docker-data/acme-companion/certs/:/etc/nginx/certs/:rw
      - ./proxy/docker-data/acme-companion/acme-state/:/etc/acme.sh/
      - /var/run/docker.sock:/var/run/docker.sock:ro

  landing:
    container_name: landing
    restart: always
    image: nginx
    environment:
      - VIRTUAL_HOST=n1.nordstud.io
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=n1.nordstud.io

  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    # Change this to your domain, it is used for your email accounts (eg: user@example.com):
    domainname: nordstud.io
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
    volumes:
      - ./mail/docker-data/dms/mail-data/:/var/mail/
      - ./mail/docker-data/dms/mail-state/:/var/mail-state/
      - ./mail/docker-data/dms/mail-logs/:/var/log/mail/
      - ./mail/docker-data/dms/config/:/tmp/docker-mailserver/
      # The volume listed below is setup to use the container "proxy-acme".
      - ./proxy/docker-data/acme-companion/certs/:/etc/letsencrypt/live/:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SSL_TYPE=letsencrypt
      - VIRTUAL_HOST=mail.nordstud.io
      - LETSENCRYPT_HOST=mail.nordstud.io

  webmail:
    image: nginx
    container_name: webmail
    environment:
      - VIRTUAL_HOST=mail.nordstud.io
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=mail.nordstud.io

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vault
    restart: always
    volumes:
      - ./vault/docker-data:/data
      - ./vault/.env:/.env
    environment:
      - VIRTUAL_HOST=vault.nordstud.io
      - LETSENCRYPT_HOST=vault.nordstud.io
